from __future__ import annotations

from .base import SourceDefinition


COMMON_INVALID_MARKERS = (
    "access denied",
    "just a moment",
    "error 404",
    "http status 404",
    "die website ist nicht erreichbar",
    "search results",
    "suchergebnisse",
)


SOURCE_DEFINITIONS = (
    SourceDefinition(
        source_id="wetteronline",
        source_name="WetterOnline",
        source_url="https://www.wetteronline.de/wetter/haltern-am-see",
        method="text",
        weight=0.95,
        horizon_days=14,
        language="de",
        location_markers=("Haltern am See",),
        invalid_markers=COMMON_INVALID_MARKERS,
    ),
    SourceDefinition(
        source_id="meteoblue",
        source_name="meteoblue",
        source_url="https://www.meteoblue.com/en/weather/today/haltern-am-see_germany_2911396",
        method="html",
        weight=0.9,
        horizon_days=14,
        language="en",
        location_markers=("Haltern am See",),
        invalid_markers=COMMON_INVALID_MARKERS,
    ),
    SourceDefinition(
        source_id="daswetter",
        source_name="Das Wetter / Meteored",
        source_url="https://www.daswetter.com/wetter_Haltern%2Bam%2BSee-Europa-Deutschland-Nordrhein%2BWestfalen--1-26703.html",
        method="text",
        weight=0.87,
        horizon_days=14,
        language="de",
        location_markers=("Haltern am See",),
        invalid_markers=COMMON_INVALID_MARKERS,
    ),
    SourceDefinition(
        source_id="timeanddate",
        source_name="timeanddate",
        source_url="https://www.timeanddate.com/weather/germany/haltern-am-see/hourly",
        method="html",
        weight=0.84,
        horizon_days=14,
        language="en",
        location_markers=("Haltern am See",),
        invalid_markers=COMMON_INVALID_MARKERS,
    ),
    SourceDefinition(
        source_id="weathercom",
        source_name="weather.com",
        source_url="https://weather.com/de-DE/wetter/stundlich/l/4f2a336086cc19d90f233d01483a462f5d7537133fe126349db13fb3727b75d6",
        method="html",
        weight=0.86,
        horizon_days=10,
        language="de",
        location_markers=("Haltern am See",),
        invalid_markers=COMMON_INVALID_MARKERS,
    ),
    SourceDefinition(
        source_id="yr",
        source_name="yr.no",
        source_url="https://www.yr.no/en/forecast/hourly-table/2-2911396/Germany/North%20Rhine-Westphalia/Regierungsbezirk%20M%C3%BCnster/Haltern%20am%20See",
        method="html",
        weight=0.79,
        horizon_days=10,
        language="en",
        location_markers=("Haltern am See",),
        invalid_markers=COMMON_INVALID_MARKERS,
    ),
    SourceDefinition(
        source_id="foreca",
        source_name="Foreca",
        source_url="https://www.foreca.com/102911395/Haltern-am-See-Kreis-Recklinghausen-Germany/hourly",
        method="html",
        weight=0.77,
        horizon_days=10,
        language="en",
        location_markers=("Haltern am See", "Kreis Recklinghausen"),
        invalid_markers=COMMON_INVALID_MARKERS,
    ),
    SourceDefinition(
        source_id="msn",
        source_name="MSN Wetter",
        source_url="https://www.msn.com/de-de/wetter/vorhersage/in-Haltern-am-See,Nordrhein-Westfalen",
        method="html",
        weight=0.76,
        horizon_days=10,
        language="de",
        location_markers=("Haltern am See",),
        invalid_markers=COMMON_INVALID_MARKERS,
    ),
    SourceDefinition(
        source_id="weatherandradar",
        source_name="Weather & Radar",
        source_url="https://www.weatherandradar.com/weather/haltern-am-see/5497243",
        method="html",
        weight=0.75,
        horizon_days=10,
        language="en",
        location_markers=("Haltern am See",),
        invalid_markers=COMMON_INVALID_MARKERS,
    ),
    SourceDefinition(
        source_id="ventusky",
        source_name="Ventusky",
        source_url="https://www.ventusky.com/haltern-am-see",
        method="html",
        weight=0.74,
        horizon_days=10,
        language="de",
        location_markers=("Haltern am See",),
        invalid_markers=COMMON_INVALID_MARKERS,
    ),
)
